service: book-nestjs

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  profile: "nadtakan"


plugins:
  - serverless-plugin-typescript
  - serverless-plugin-optimize

package:
  individually: true

functions:
  main:
    handler: src/main.handler
    events:
      - http:
          method: any
          path: /{proxy+}

custom:
  optimize:
    external: ['swagger-ui-dist']